apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - arn:aws:secretsmanager:ap-southeast-2:211125781546:secret:testscret1-1fOePl
