apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-cluster-ingress
  namespace: aws-app-ns
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - aws.thomaszou2077.com
      secretName: aws-cluster-tls-secret
  rules:
    - host: aws.thomaszou2077.com
      http:
        paths:
          - path: 1
            pathType: Prefix
            backend:
              service:
                name: aws-cluster-svc
                port:
                  number: 80