apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cluster-deployment
  namespace: aws-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cluster-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aws-cluster-app
        aadpodidbinding: 1
    spec:
      containers:
        - name: aws-cluster
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: Name 
              value: /mnt/secrets-store/Name
          ports: 
            - containerPort: 80
          volumeMounts:
            - mountPath: /mnt/secrets-store 
              name: secrets-store-inline 
              readOnly: true 
          resources:
           limits:
             memory: 512Mi
             cpu: "0.25"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-app-keyvault-spc
        