apiVersion: v1
kind: Service
metadata:
  name: saas-core-local-front-svc
  namespace: saas-core-local-ns
spec:
  selector:
    app:  saas-core-local-front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: saas-core-local-keyvault-spc
  namespace: saas-core-local-ns
spec:
  provider: aws
  parameters:
    region: ap-southeast-2 # 替换为你的 AWS 区域
    objects: |
      array:
        - |
          objectType: secretsmanager
          objectName: testscret1
          objectAlias: keyone
  secretObjects:
    - secretName: saas-core-local-secret
      type: Opaque
      data:
        - key: keyone
          objectName: keyone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-core-local-front-deployment
  namespace: saas-core-local-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-core-local-front-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: saas-core-local-front-app
        aadpodidbinding: saas-pod-identity
    spec:
      containers:
        - name: saas-core-local-front
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: keyone
              value: /mnt/secrets-store/keyone
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /mnt/secrets-store
              name: secrets-store-inline
              readOnly: true
          resources:
            limits:
              memory: 256Mi
              cpu: "0.125"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: saas-core-local-keyvault-spc
