apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-test-deployment
  namespace: test-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-test-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cluster-test-app
        aadpodidbinding: saas-pod-identity
    spec:
      containers:
        - name: cluster-test
          image: djpsaascoreacr.azurecr.io/saas-api:24.2.8.37
          imagePullPolicy: Always
          env:
            - name: conf1
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: conf1
            - name: KeyVaultOne
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: KeyVaultOne
            - name: TiDB-odbc-connector
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: TiDB-odbc-connector
            - name: SendGridKey
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: SendGridKey
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /mnt/secrets-store
              name: secrets-store-inline
              readOnly: true
            - mountPath: /dv1
              name: cluster-test-808-pvc
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: cluster-test-808-pvc
          persistentVolumeClaim:
            claimName: cluster-test-808-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: test-app-keyvault-spc
        