apiVersion: v1
kind: Service
metadata:
  name: cluster-test-svc
  namespace: test-app-ns
spec:
  selector:
    app:  cluster-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-test-deployment
  namespace: test-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-test-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cluster-test-app
        aadpodidbinding:
    spec:
      containers:
        - name: cluster-test
          image: djpest.azurecr.io/ssflow-api:0.0.1
          imagePullPolicy: Always
          env:
            - name: conf
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: conf
            - name: keyvault-two
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: keyvault-two
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /dv1
              name: cluster-test-446-pvc
            - mountPath: /dv2
              name: cluster-test-533-pvc
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
      volumes:
        - name: cluster-test-446-pvc
          persistentVolumeClaim:
            claimName: cluster-test-446-pvc
        - name: cluster-test-533-pvc
          persistentVolumeClaim:
            claimName: cluster-test-533-pvc
        - name: cluster-test-384-pvc
          persistentVolumeClaim:
            claimName: cluster-test-384-pvc
        - name: cluster-test-549-pvc
          persistentVolumeClaim:
            claimName: cluster-test-549-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: test-app-keyvault-spc
            nodePublishSecretRef:
              name:  test-app-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-test-configmap
  namespace: test-app-ns
data:
  conf: "2"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-test-ingress
  namespace: test-app-ns
spec:
  tls:
    - hosts:
        - thomas01.thomaszou2077.com
      secretName: cluster-test-tls-secret
  rules:
    - host: thomas01.thomaszou2077.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-test-svc
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-446-pvc
  namespace: test-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  volumeName: pv-cluster-test-0
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-533-pvc
  namespace: test-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  volumeName: pv-cluster-test-1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-384-pvc
  namespace: test-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  volumeName: pv-cluster-test-2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-549-pvc
  namespace: test-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  volumeName: pv-cluster-test-3
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-cluster-test-0
spec:
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/277809f3-155d-4b95-b44e-698844918adb/resourceGroups/saas-core/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-cluster-test-1
spec:
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/277809f3-155d-4b95-b44e-698844918adb/resourceGroups/saas-core/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-cluster-test-2
spec:
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/277809f3-155d-4b95-b44e-698844918adb/resourceGroups/saas-core/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-cluster-test-3
spec:
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/277809f3-155d-4b95-b44e-698844918adb/resourceGroups/saas-core/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-app-keyvault-spc
  namespace: test-app-ns
spec:
  parameters:
    keyvaultName: keyvault-one
    objects: |
      array:
        - | 
          objectType: secret 
          objectName: x22 
    tenantId: "1bf2b880-115d-4e08-a258-aa1dc41dc0d5"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "277809f3-155d-4b95-b44e-698844918adb"
  provider: azure
  secretObjects:
    - secretName: test-app-secret
      type: Opaque
      data:
        - key: x22
          objectName: x22 
