apiVersion: v1
kind: Secret
metadata:
  name: pssql-secret
  namespace: pssql-ns
  labels:
    secrets-store.csi.k8s.io/managed: "true"
    secrets-store.csi.k8s.io/used: "true"
type: Opaque

#2c2ac4ec-4c6e-4b0f-b3c7-8f1e43a4c529
#ce39c546-18a5-4362-a4ab-8c5a6ee6e8a9