apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pssql-keyvault-spc
  namespace: pssql
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    tenantId: 1bf2b880-115d-4e08-a258-aa1dc41dc0d5
    keyvaultName: kut-kv-zy # Azure Key Vault 的名称
    userAssignedIdentityID: cf123f25-f97a-4617-8103-9509b14bd351 # 页面上的ManagedID
    objects: |
      array:
        - | 
          objectType: secret  
          objectName: KeyVaultOne   
        - |
          objectType: secret          
          objectName: keyvault-twp       
  secretObjects:
    - secretName: pssql-secret # Kubernetes Secret 的名称 
      type: Opaque
      data:
        - key: KeyVaultOne  # Kubernetes Secret 中的键
          objectName:  KeyVaultOne  # Azure Key Vault 中的秘密名称
        - key: kv2  # Kubernetes Secret 中的键
          objectName: keyvault-twp  # Azure Key Vault 中的秘密名称
    
      
# kubectl get secret pssql-secret -n pssql-ns
  # kubectl delete secretproviderclass pssql-keyvault-spc -n pssql-ns