apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pssql-keyvault-spc
  namespace: pssql-ns
spec:
  provider: azure
  parameters:
    usePodIdentity: 'true'
    useVMManagedIdentity: 'false'
    tenantId: '1bf2b880-115d-4e08-a258-aa1dc41dc0d5'
    keyvaultName: test-kv-zy
    userAssignedIdentityID: '277809f3-155d-4b95-b44e-698844918adb' # 页面上的ManagedID
    objects: |
      array:
        - |          
          objectName: keyvault-one
          objectType: secret  
  secretObjects:
    - secretName: pssql-secret # Kubernetes Secret 的名称 
      type: Opaque
      data:
        - key: KeyVaultOne  # Kubernetes Secret 中的键
          objectName:  keyvault-one  # Azure Key Vault 中的秘密名称
