
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-test-configmap
  namespace: test-app-ns
data:
  ApiDynamicHandler: "https://aeonapipo.azurewebsites.net/WF/Comm/Handler.ashx?"
  AppCenterDSN: "Server=4.241.26.23;Port=4000;Database=Saas_Core;Uid=root;Pwd=;AllowUserVariables=True;MaxPoolSize=2000"
  ENVIRONMENT: "dev"
  BaseUrl: "https://saascore.thomaszou2077.com/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-40-pvc
  namespace: test-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-test-deployment
  namespace: test-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-test-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cluster-test-app
        aadpodidbinding: saas-pod-identity
    spec:
      containers:
        - name: cluster-test
          image: djpsaascoreacr.azurecr.io/saas-api:24.2.8.37
          imagePullPolicy: Always
          env:
            - name: ApiDynamicHandler
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: ApiDynamicHandler
            - name: AppCenterDSN
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: AppCenterDSN
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: ENVIRONMENT
            - name: BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: cluster-test-configmap
                  key: BaseUrl
            - name: KeyVaultOne
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: KeyVaultOne
            - name: TiDB-odbc-connector
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: TiDB-odbc-connector
            - name: SendGridKey
              valueFrom:
                secretKeyRef:
                  name: test-app-secret
                  key: SendGridKey
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /mnt/secrets-store
              name: secrets-store-inline
              readOnly: true
            - mountPath: /dv1
              name: cluster-test-40-pvc
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: cluster-test-40-pvc
          persistentVolumeClaim:
            claimName: cluster-test-40-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: test-app-keyvault-spc
        